const names = {
  1: {
    it:"Pugno di ferro in un guanto di velluto! Sei molto determinata e a volte questo carattere ti porta a commettere errori di cui ti penti in seguito. Non riesci a tenerti dentro quello che senti, ma hai il pregio di mettere le carte in tavola e i tuoi amici lo sanno e ti stimano per questo! Sanno che possono contare su di te. Sei una persona leale e circondata di amici: rivendichi la tua indipendenza ma non sopporti che gli altri si allontanino da te, odi la solitudine. In amore, non hai nessuna difficoltà ad esprimere i tuoi sentimenti. Invece, sul lavoro, sei una che si dà da fare e sei molto ambiziosa. A volte, i tuoi colleghi ti possono giudicare opportunista… La tua creatività ti porta a scegliere lavori artistici a meno che tu non preferisca la strada imprenditoriale.",
    en:"Iron fist in a velvet glove! You are very determined and sometimes this character leads you to make mistakes that you regret later. You can't keep what you feel inside, but you have the merit of putting your cards on the table and your friends know it and respect you for it! They know they can count on you. You are a loyal person and surrounded by friends: you claim your independence but you can't stand that others leave you, you hate loneliness. In love, you have no difficulty expressing your feelings. Instead, at work, you are a busy person and you are very ambitious. Sometimes, your colleagues may judge you as an opportunist… Your creativity leads you to choose artistic works unless you prefer the entrepreneurial path."
  },
  2: {
    it:"Al primo impatto, ti possono giudicare riservata e distante. Però lo pensa solo chi non ti conosce bene perché sotto il tuo aspetto freddo, sei ultra sensibile! Il sarcasmo e l'ironia ti proteggono dalle delusioni… Quante volte hai dato la tua fiducia a chi non la meritava? In amore, sei alla ricerca di qualcuno che sappia capirti e (soprattutto) proteggerti. Sensuale, sai usare e giocare con il tuo fascino per far innamorare il tuo partner. Ma attenzione, per te il matrimonio è sacro perché dentro di te sai di essere una persona romantica.",
    en:"At first glance, they may judge you reserved and distant. But only those who don't know you well think so because under your cold appearance, you're ultra sensitive! Sarcasm and irony protect you from disappointment... How many times have you given your trust to someone who didn't deserve it? In love, you are looking for someone who can understand you and (above all) protect you. Sensual, you know how to use and play with your charm to make your partner fall in love with you. But beware, marriage is sacred to you because deep down you know you are a romantic person."
  },
  3: {
    it:"Hai l'anima e lo spirito di una artista! Disegno, ballo, canto, ecc. Riesci a realizzarti nelle attività creative e hai un'immaginazione fervida. Il tuo intuito è il tuo sesto senso e ti affidi totalmente a lui per prendere le tue decisioni. Tuttavia, in amore e sul lavoro, sai essere pragmatica e non sopporti né l'ipocrisia né le chiacchiere. Con te, le soluzioni devono essere concrete e immediate. Sei una persona curiosa e sei attratta dalle esperienze insolite. In amore, sei volubile e ti piace cambiare partner finché non incontri il vero amore. Ma prima di ammetterlo nel tuo cuore, gli farai passare una serie di test! Sul lavoro, sei prima di tutto alla ricerca di un riconoscimento morale. Senti il bisogno di essere incoraggiata e sostenuta per riuscire a dare il meglio di te. Ma attenzione: devi imparare a distinguere i complimenti sinceri dalle lodi esagerate e false.",
    en:"You have the soul and spirit of an artist! Drawing, dancing, singing, etc. You are thriving in creative pursuits and have a vivid imagination. Your intuition is your sixth sense and you rely totally on it to make your decisions. However, in love and at work, you know how to be pragmatic and can't stand hypocrisy or gossip. With you, the solutions must be concrete and immediate. You are a curious person and are attracted to unusual experiences. In love, you are fickle and like to switch partners until you meet true love. But before you admit it to your heart, you'll put it through a series of tests! At work, you are primarily looking for moral recognition. You feel the need to be encouraged and supported to be able to give your best. But be careful: you must learn to distinguish sincere compliments from exaggerated and false praise."
  },
  4: {
    it:"La spontaneità non è il tuo forte. Nella vita, tutto deve essere sistemato, organizzato, pianificato sennò vai in tilt! Sul lavoro, temi le responsabilità: preferisci essere comandato e guidato da un capo e non ami prendere decisioni.  La  tua innata prudenza ti spinge a non avventurarti in campi sconosciuti. Idem in amore: hai bisogno di tanto tempo prima di lasciarti andare. Tuttavia, una volta trovato il grande amore, ti senti a tuo agio nel tuo nido d'amore, sai sostenere il tuo partner e aiutarlo a realizzare le sue ambizioni. Il tuo sogno è avere tanti bambini. Il tuo rapporto con i soldi. Sei una formica: risparmi con prudenza e non sei quasi mai in rosso. Ma quando succede, il tuo senso pragmatico ti aiuta a risolvere velocemente la situazione.",
    en:"Spontaneity is not your forte. In life, everything has to be fixed, organised, planned otherwise you go haywire! At work, you fear responsibilities: you prefer to be commanded and guided by a boss and you don't like making decisions. Your innate prudence pushes you not to venture into unknown fields. Ditto in love: you need a lot of time before letting go. However, once you find great love, you feel comfortable in your love nest, you know how to support your partner and help them achieve their ambitions. Your dream is to have many children. Your relationship with money. You're an ant: save carefully and you're almost never in the red. But when it does, your pragmatic sense helps you resolve the situation quickly."
  },
  5: {
    it:"Ti piace il cambiamento, l'imprevisto e la novità. Sei una persona molto curiosa e sei decisa a provare tutto! Anche le esperienze insolite e da brivido non ti fanno paura. Adolescente ribelle, hai deciso molto presto di assumerti le tue responsabilità. Al primo impatto, puoi sembrare una persona timida ma sai mantenere il sangue freddo nelle situazioni più difficili. Sul piano affettivo, non accetti i compromessi. Ami molto, passionalmente, alla follia o per niente. Non esistono, per te, le mezze misure.Sul lavoro, sei attratta dal settore turistico e dalla libera professione per mantenere la tua indipendenza.",
    en:"You like change, the unexpected and novelty. You are a very curious person and you are determined to try everything! Even unusual and thrilling experiences don't scare you. Rebellious teenager, you decided very early on to take your responsibilities. At first glance, you may seem like a shy person but you know how to keep a cool head in the most difficult situations. Emotionally, you don't accept compromises. You love a lot, passionately, madly or not at all. There are no half measures for you. At work, you are attracted to the tourism sector and the free profession to maintain your independence."
  },
  6: {
    it:"Sogni e aspetti il principe azzurro. Perdi la testa per le dichiarazioni d'amore passionali e hai bisogno di tenerezza e di parole dolci per sentirti soddisfatta. Attenzione però, il tuo essere indecisa potrebbe turbare il tuo partner. Infatti, spesso non riesce a capire le tue emozioni e motivazioni. E' in famiglia che riesci ad esprimere al meglio la tua sensibilità e a farti capire. Ma, nel profondo del tuo cuore, hai sogni grandiosi… ma irrealizzabili. Il consiglio è di non chiuderti e non allontanarti dalla realtà per non sprecare i tuoi talenti. Per fortuna hai la capacità di circondarti di persone di fiducia che ti aiutano a tenere i piedi per terra. Sul lavoro, ti rimproverano a volte di essere distante. Invece, a livello economico, soffri spesso della sindrome da shopping compulsivo e dopo ti colpevolizzi.",
    en:"You dream and wait for Prince Charming. You lose your head over passionate declarations of love and you need tenderness and sweet words to feel satisfied. But be careful, your being indecisive could upset your partner. In fact, often you don't he can understand your emotions and motivations. It is in the family that you are able to best express your sensitivity and make yourself understood. But, in the depths of your heart, you have grandiose dreams... but they cannot be achieved. The advice is not to shut yourself away and not to distance yourself from reality so as not to waste your talents. Fortunately, you have the ability to surround yourself with trusted people who help you keep your feet on the ground. At work, they sometimes reproach you for being distant. Instead, economically, you often suffer from compulsive shopping syndrome and then you blame yourself."
  },
  7: {
    it:"La gente può giudicarti ambigua e enigmatica al primo impatto ma hai capacità di osservazione e analisi incredibili. D'altronde, tu sei quella che consiglia i tuoi amici e loro seguono i tuoi consigli alla lettera! Parenti e amici pensano che tu sia una persona malinconica ma invece sei solo concentrata su te stessa per riuscire a capire te stessa. Infatti, sei la regina dell'introspezione. In amore, per te, non esistono colpi di fulmine né separazioni: per te, tutto è già scritto! Peccato che a volte non ti lasci andare e scappi di fronte alle tue emozioni.  Potresti rinunciare ad una bella storia d'amore per paura.Professionalmente, sei una studiosa e ti iscrivi a lezioni on line per approfondire le tue conoscenze. Devi i tuoi successi solo alla tua perseveranza.",
    en:"People may judge you ambiguous and enigmatic at first sight but you have incredible powers of observation and analysis. After all, you are the one who recommends your friends and they follow your advice to the letter! Relatives and friends think you are a melancholy person but instead you are only focused on yourself to be able to understand yourself. Indeed, you are the queen of introspection. In love, for you, there are no love at first sight or separations: for you, everything is already written! Too bad that sometimes you don't let yourself go and run away from your emotions. You could give up a beautiful love story out of fear. Professionally, you are a scholar and you sign up for online classes to deepen your knowledge. You owe your successes only to your perseverance."
  },
  8: {
    it:"Sei una persona piena di progetti e hai l'anima di un capo perché ti piace comandare e d'altronde gli altri ti ascoltano sempre. Tutti ti stimano ma ti temono perché sei molto impulsiva e non temi di prendere rischi per raggiungere i tuoi obiettivi. Anche in amore, sei tu che comandi e riesci a convincere il tuo partner a seguirti a occhi chiusi. Invecchiando, diventi più morbida con te e gli altri. Impari a lasciarti andare e a vivere seguendo le tue emozioni.",
    en:"You are a person full of projects and you have the soul of a boss because you like to be in charge and on the other hand the others always listen to you. Everyone respects you but fears you because you are very impulsive and you are not afraid to take risks to achieve your goals. Even in love, you are in charge and manage to convince your partner to follow you with their eyes closed. As you get older, you become softer with yourself and with others. You learn to let go and live with your emotions."
  },
  9: {
    it:"Sogni un mondo pacifico e idealista. Sei vulnerabile di fronte alle bugie e al tradimento. Tuttavia, quando ci sono problemi, non sei passiva di fronte alle situazioni complesse, sei in grado di combattere per risolverle. Sul lavoro, agisci con metodo e costanza. Difendi e porti avanti con determinazione i progetti nei quali credi. Attenzione però a non essere manipolata sul lavoro, alcuni potrebbero approfittare della tua incredibile dedizione al lavoro per importi un ritmo frenetico. I tuoi amici sanno che posso contare su di te perché sai ascoltare e consigliare. In amore, alcune brutte esperienze ti hanno lasciato cicatrici aperte. Non credi più nel grande amore e non accetti che qualcuno possa giocare con i tuoi sentimenti! Coraggio, prima o poi, troverai la tua anima gemella…",
    en:"You dream of a peaceful and idealistic world. You are vulnerable to lies and betrayal. However, when there are problems, you are not passive in the face of complex situations, you are able to fight to solve them. At work, act methodically and consistently. Defend and carry forward the projects you believe in with determination. But be careful not to be manipulated at work, some may take advantage of your incredible dedication to work to impose a frenetic pace. Your friends know that I can count on you because you know how to listen and advise. In love, some bad experiences have left you with open scars. You no longer believe in great love and you don't accept that someone can play with your feelings! Courage, sooner or later, you will find your soul mate…"
  },
};

module.exports = names;
